USE BD_MATRICULA;

SELECT * FROM ESTUDIANTES;

SELECT NOMBRE_ESTUDIANTE, CARNET
FROM ESTUDIANTES;

SELECT USUARIO_MATRICULA FROM MATRICULAS;
SELECT DISTINCT USUARIO_MATRICULA FROM MATRICULAS;

SELECT USUARIO_MATRICULA, OBSERVACIONES_MATRICULAS FROM MATRICULAS;
SELECT DISTINCT USUARIO_MATRICULA, OBSERVACIONES_MATRICULAS FROM MATRICULAS;

SELECT ID_ESTUDIANTE
FROM ESTUDIANTES
WHERE NOMBRE_ESTUDIANTE = 'DAVID';

-- Nota: mostrará todos los registros cuyo nombre sea DAVID

SELECT ID_ESTUDIANTE, NOMBRE_ESTUDIANTE, PRIMER_APELLIDO_E
FROM ESTUDIANTES
WHERE ID_ESTUDIANTE = '208110229';

-- Nota: Mostrará solo un resultado porque estamos llamando a la llave primaria, la cual es Única

SELECT NOMBRE_ESTUDIANTE
FROM ESTUDIANTES
WHERE FECHA_INGRESO < '20210328';

SELECT NOMBRE_ESTUDIANTE, PRIMER_APELLIDO_E, FECHA_INGRESO
FROM ESTUDIANTES
WHERE FECHA_INGRESO < '20210328';

-- Puede cambiar los símbolos po > para que observe el resultado

SELECT NOMBRE_ESTUDIANTE, FECHA_INGRESO
FROM ESTUDIANTES
WHERE MONTH(FECHA_INGRESO) >= 1
  AND MONTH(FECHA_INGRESO) <= 3
  AND YEAR(FECHA_INGRESO) = 2021;

  
SELECT NOMBRE_ESTUDIANTE, FECHA_INGRESO
FROM ESTUDIANTES
WHERE MONTH(FECHA_INGRESO) >= 4
  AND MONTH(FECHA_INGRESO) <= 7
  AND YEAR(FECHA_INGRESO) = 2021;

  
SELECT NOMBRE_ESTUDIANTE, FECHA_INGRESO
FROM ESTUDIANTES
WHERE MONTH(FECHA_INGRESO) >= 1
  AND MONTH(FECHA_INGRESO) <= 3
  AND YEAR(FECHA_INGRESO) = 2020;

-- Selecciona quienes tienen BECA A o BECA B
SELECT CARNET
FROM MATRICULAS
WHERE OBSERVACIONES_MATRICULAS IN ('BECA A', 'BECA C');

-- Seleciona a los estudiantes ACTIVOS y los INACTIVOS
SELECT NOMBRE_ESTUDIANTE, PRIMER_APELLIDO_E, ESTADO
FROM ESTUDIANTES
WHERE ESTADO IN ('ACT','INA');

-- Mostrar los registros cuyo monto esté entre 50 mil y 100 mil
SELECT CARNET, MONTO
FROM MATRICULAS
WHERE MONTO BETWEEN 50000 AND 100000;

-- Mostrar los registros cuya fecha esté entre el 1 de abril y el 1 de agosto
SELECT CARNET, NOMBRE_ESTUDIANTE, FECHA_INGRESO
FROM ESTUDIANTES
WHERE FECHA_INGRESO BETWEEN '20210401' AND '20210801';

-- Seleccionar todos los apellidos que inician con V
SELECT PRIMER_APELLIDO_E, NOMBRE_ESTUDIANTE, CARNET
FROM ESTUDIANTES
WHERE PRIMER_APELLIDO_E LIKE 'V%';

-- Seleccionar todos los apellidos que NO inician con V
SELECT PRIMER_APELLIDO_E, NOMBRE_ESTUDIANTE, CARNET
FROM ESTUDIANTES
WHERE PRIMER_APELLIDO_E NOT LIKE 'V%';

-- Seleccionar los apellidos que CONTIENEN una letra A
SELECT NOMBRE_ESTUDIANTE, PRIMER_APELLIDO_E
FROM ESTUDIANTES
WHERE PRIMER_APELLIDO_E LIKE '%A%';

-- Seleccionar los apellidos que NO CONTIENEN una letra A
SELECT NOMBRE_ESTUDIANTE, PRIMER_APELLIDO_E
FROM ESTUDIANTES
WHERE PRIMER_APELLIDO_E NOT LIKE '%A%';

-- IS NOT NULL
SELECT *
FROM MATRICULAS
WHERE OBSERVACIONES_MATRICULAS IS NOT NULL;

-- ORDER BY
-- Mostrar los campos ordenados de forma descendente por NOMBRE
SELECT PRIMER_APELLIDO_E, SEGUNDO_APELLIDO_E, NOMBRE_ESTUDIANTE
FROM ESTUDIANTES
ORDER BY NOMBRE_ESTUDIANTE DESC;

-- Mostrar los datos con dos criterios de ordenamiento y condición WHERE
SELECT PRIMER_APELLIDO_E, SEGUNDO_APELLIDO_E, NOMBRE_ESTUDIANTE
FROM ESTUDIANTES
WHERE PRIMER_APELLIDO_E LIKE 'V%'
ORDER BY PRIMER_APELLIDO_E ASC,
NOMBRE_ESTUDIANTE ASC;

-- Ordenar indicando el NÚMERO DE COLUMNA
SELECT *
FROM ESTUDIANTES
ORDER BY 3 DESC;

