CREATE DATABASE EJEMPLO_BD
GO

USE EJEMPLO_BD;

CREATE TABLE ESTUDIANTES(
	ID_Estudiante int IDENTITY(1,1) CONSTRAINT PK_EST PRIMARY KEY,
	NOMBRE varchar(25) NOT NULL,
	APELLIDOS varchar(25) DEFAULT 'Alajuela' NOT NULL
);

--DROP TABLE ESTUDIANTES;

-- SELECT * FROM ESTUDIANTES;

--ALTER TABLE ESTUDIANTES