CREATE DATABASE BD_AUTOS
GO

USE BD_AUTOS;


-- ******************* CREACIÓN Y MODIFICACIÓN DE TABLAS *****************

CREATE TABLE AUTOS_INVENTARIO(
			 PLACA_AUTO varchar(15) CONSTRAINT PK_PLACA_AUTO PRIMARY KEY,
			 COLOR varchar(20) NOT NULL,
			 ANIO smallint NOT NULL,
			 ESTADO varchar(25) NOT NULL,
			 PUERTAS smallint NOT NULL
);


CREATE TABLE AUTOS_PARA_VENDER(
			 PLACA_AUTO varchar(15) CONSTRAINT PK_PLACA_AUTO_2 PRIMARY KEY,
			 COLOR varchar(20) NOT NULL,
			 ANIO smallint NOT NULL,
			 ESTADO varchar(25) NOT NULL,
			 PUERTAS smallint NOT NULL
);

CREATE TABLE CHOFERES (
			 ID_CHOFER varchar(15) CONSTRAINT PK_ID_CHOFER PRIMARY KEY,
			 NOMBRE_CHOFER varchar(25) NOT NULL,
			 APELLIDO1 varchar(25) NOT NULL,
			 APELLIDO2 varchar(25) NOT NULL,
			 LICENCIA varchar(25) NOT NULL
);

CREATE TABLE ASIGNACION_CHOFERES(
			 PLACA_AUTO varchar(15) NOT NULL,
			 ID_CHOFER varchar(15) NOT NULL
);


-- ********************** LLAVES SEGUNDARIAS ***********************

ALTER TABLE ASIGNACION_CHOFERES
	ADD CONSTRAINT FK_PLACA_AUTO FOREIGN KEY (PLACA_AUTO) REFERENCES AUTOS_INVENTARIO(PLACA_AUTO);

ALTER TABLE ASIGNACION_CHOFERES
	ADD CONSTRAINT FK_ID_CHOFER FOREIGN KEY (ID_CHOFER) REFERENCES CHOFERES(ID_CHOFER);


-- ********************** AGREGAR REGISTROS ************************

INSERT INTO AUTOS_INVENTARIO (PLACA_AUTO,
							  COLOR,
							  ANIO,
							  ESTADO,
							  PUERTAS)
		VALUES('BDW245', 'NEGRO', 1995, 'ENTERO', 4),
			  ('PDC300', 'BLANCO', 2011, 'ENTERO', 2),
			  ('RDW282', 'AZUL', 2020, 'ENTERO', 4),
			  ('QWL412', 'ROJO', 2021, 'ENTERO', 2),
			  ('PLL145', 'GRIS', 1999, 'ENTERO', 2),
			  ('WTS025', 'AMARILLO', 2000, 'ENTERO', 4),
			  ('LLP275', 'NEGRO', 2001, 'ENTERO', 2),
			  ('BDW505', 'AZUL', 2021, 'ENTERO', 4);


INSERT INTO CHOFERES (ID_CHOFER,
					  NOMBRE_CHOFER,
					  APELLIDO1,
					  APELLIDO2,
					  LICENCIA)
		VALUES('208250591', 'Gustavo', 'Ruiz', 'Jimenez', 'B1'),
			  ('109950590', 'Melanni', 'Salas', 'Cubero', 'B1'),
			  ('207250791', 'Julio', 'Arias', 'Hidalgo', 'B1'),
			  ('109250592', 'Felix', 'Segura', 'Gomez', 'B1'),
			  ('202250593', 'Martina', 'Lopez', 'Araya', 'B1'),
			  ('208850594', 'Jimena', 'Mora', 'Solis', 'B1'),
			  ('107750544', 'Pier', 'Nuñez', 'Jimenez', 'B1');

INSERT INTO ASIGNACION_CHOFERES (PLACA_AUTO,
								 ID_CHOFER)
		VALUES('BDW245', '109950590'),
			  ('LLP275', '107750544'),
			  ('WTS025', '207250791'),
			  ('QWL412', '202250593');



-- ************************ CONSULTAS *****************************


INSERT INTO AUTOS_PARA_VENDER(PLACA_AUTO, COLOR, ANIO, ESTADO, PUERTAS)
		SELECT PLACA_AUTO, COLOR, ANIO, ESTADO, PUERTAS
		FROM AUTOS_INVENTARIO
		WHERE ANIO > 2015;


SELECT * FROM AUTOS_INVENTARIO;

SELECT * FROM AUTOS_PARA_VENDER;

DELETE FROM AUTOS_INVENTARIO
	WHERE ANIO > 2015;

--------------------- ACTIVIDAD A --------------------------------------

SELECT AC.PLACA_AUTO, COLOR, ANIO, NOMBRE_CHOFER, APELLIDO1, APELLIDO2

FROM CHOFERES C INNER JOIN ASIGNACION_CHOFERES AC
	ON C.ID_CHOFER = AC.ID_CHOFER

	INNER JOIN AUTOS_INVENTARIO AI
	ON AC.PLACA_AUTO = AI.PLACA_AUTO;


------------------- ACTIVIDAD B --------------------------------------


SELECT AC.PLACA_AUTO, COLOR, ANIO, NOMBRE_CHOFER, APELLIDO1, APELLIDO2

FROM CHOFERES C INNER JOIN ASIGNACION_CHOFERES AC
	ON C.ID_CHOFER = AC.ID_CHOFER

	INNER JOIN AUTOS_INVENTARIO AI
	ON AC.PLACA_AUTO = AI.PLACA_AUTO

WHERE ANIO > 2018;
