/* INA - Centro de Formación Profesional de San Ramón

Gestión de Bases de Datos
	01/06/2021
Redwin Valverde Castro

*/

CREATE DATABASE BD_MATRICULA
GO

USE BD_MATRICULA;

-- _______________________________ Creación de Tablas: _______________________________

CREATE TABLE CARRERAS(
	COD_CARRERA int IDENTITY(1,1),
	NOMBRE_CARRERA varchar(100) NOT NULL,
	TOTAL_CREDITOS smallint NOT NULL,
	GRADO varchar(14) NOT NULL,
);

CREATE TABLE ESTUDIANTES(
	CARNET varchar(6),
	ID_ESTUDIANTE varchar(20) NOT NULL,
	NOMBRE_ESTUDIANTE varchar(25) NOT NULL,
	PRIMER_APELLIDO_E varchar(20) NOT NULL,
	SEGUNDO_APELLIDO_E varchar(20),
	TELEFONO_ESTUDIANTE varchar(11) NOT NULL,
	CORREO_ESTUDIANTE varchar(25),
	FECHA_INGRESO datetime NOT NULL,
	ESTADO varchar(3) NOT NULL,
	BORRADO_EST bit NOT NULL
);

CREATE TABLE PROFESORES(
	COD_PROFESOR int IDENTITY(1,1),
	ID_PROFESOR varchar(15) NOT NULL,
	NOMBRE_PROFESOR varchar(25) NOT NULL,
	PREIMER_APELLIDO_P varchar(20) NOT NULL,
	SEGUNDO_APELLIDO_P varchar(20) NOT NULL,
	TELEFONO_PROFESOR varchar(8) NOT NULL,
	CORREO_PROFESOR varchar(25) NOT NULL,
	BORRADO_PROF bit NOT NULL
);

CREATE TABLE MATERIAS(
	COD_MATERIA varchar(10),
	NOMBRE_MATERIA varchar(120) NOT NULL,
	CREDITOS tinyint NOT NULL,
	BORRADO_MATERIAS bit NOT NULL
);

CREATE TABLE MATERIAS_CARRERAS(
	COD_MATERIA_CARRERA int IDENTITY(1,1),
	COD_CARRERA int NOT NULL,
	COD_MATERIA varchar(10) NOT NULL,
	REQUISITO varchar(10),
	CORREQUISITO varchar(10),
	BORRADO_MAT_CAR bit NOT NULL
);

CREATE TABLE MATERIAS_ABIERTAS(
	COD_MATERIA_ABIERTA int IDENTITY(1,1),
	COD_MATERIA_CARRERA int,
	COD_PROFESOR int,
	GRUPO tinyint,
	CUPO tinyint NOT NULL,
	COSTO decimal(10,2),
	PERIODO tinyint NOT NULL,
	ANIO smallint NOT NULL,
	MAXIMO_DESCUENTO decimal(4,2)
);

CREATE TABLE HORARIOS(
	COD_MATERIA_ABIERTA int,
	DIA varchar(1),
	HORA_INICIO datetime,
	HORA_FIN datetime
);

CREATE TABLE MATRICULAS(
	NUM_RECIBO int IDENTITY(1,1),
	CARNET varchar(6) NOT NULL,
	FECHA datetime NOT NULL,
	MONTO decimal(10,2) NOT NULL,
	DESCUENTO decimal(10,2),
	ESTADO varchar(3) NOT NULL,
	USUARIO_MATRICULA varchar(25) NOT NULL,
	OBSERVACIONES_MATRICULAS varchar(250)
);

CREATE TABLE DETALLE_MATRICULAS(
	NUM_RECIBO int,
	COD_MATERIA_ABIERTA int,
	PORCENTAJE_DESCUENTO decimal(4,2),
	NOTA_FINAL decimal(5,2),
	ESTADO varchar(3) NOT NULL,
	OBSERVACIONES_DET_MATRICULAS varchar(500)
);

-- _______________________________ Modificacion de Tablas: _______________________________

-- CARRERAS

ALTER TABLE CARRERAS
	ADD CONSTRAINT PK_CARRERAS PRIMARY KEY (COD_CARRERA),
	CONSTRAINT CHK_TOTAL_CREDITOS CHECK (TOTAL_CREDITOS > 0 AND TOTAL_CREDITOS < 1000),
	CONSTRAINT DF_GRADO DEFAULT 'Bachillerato' FOR GRADO,
	CONSTRAINT CHK_GRADO CHECK (GRADO = upper(GRADO) AND GRADO IN ('LICENCIATURA','BACHILLERATO','DIPLOMADO','MAESTRIA'));

-- ESTUDIANTES

ALTER TABLE ESTUDIANTES
	ADD CONSTRAINT PK_ESTUDIANTES PRIMARY KEY (CARNET),
	CONSTRAINT UNICO_ID_ESTUDIANTE UNIQUE (ID_ESTUDIANTE),
	CONSTRAINT CHK_FECHA_INGRESO CHECK (FECHA_INGRESO >= getdate()),
	CONSTRAINT DF_ESTADO DEFAULT 'INA' FOR ESTADO,
	CONSTRAINT CHK_ESTADO CHECK (ESTADO = upper(ESTADO) AND ESTADO IN ('INA','ACT')),
	CONSTRAINT DF_BORRADO_EST DEFAULT 0 FOR BORRADO_EST;

-- PROFESORES

ALTER TABLE PROFESORES
	ADD CONSTRAINT PK_PROFESOR PRIMARY KEY (COD_PROFESOR),
	CONSTRAINT UNICO_ID_PROFESOR UNIQUE (ID_PROFESOR),
	CONSTRAINT DF_BORRADO_PROF DEFAULT 0 FOR BORRADO_PROF;

-- MATERIAS

ALTER TABLE MATERIAS
	ADD CONSTRAINT PK_MATERIAS PRIMARY KEY (COD_MATERIA),
	CONSTRAINT CHK_CREDITOS CHECK (CREDITOS >=1 AND CREDITOS <= 11),
	CONSTRAINT DF_BORRADO_MATERIAS DEFAULT 0 FOR BORRADO_MATERIAS;

-- MATERIAS_CARRERAS

ALTER TABLE MATERIAS_CARRERAS
	ADD CONSTRAINT PK_MATERIA_CARRERA PRIMARY KEY (COD_MATERIA_CARRERA),
	CONSTRAINT DF_BORRADO_MAT_CAR DEFAULT 0 FOR BORRADO_MAT_CAR,
	CONSTRAINT FK_MT_CARRERA FOREIGN KEY (COD_CARRERA)
	REFERENCES CARRERAS (COD_CARRERA)
		ON UPDATE NO ACTION
		ON DELETE NO ACTION,
	
	CONSTRAINT FK_MT_COD_MATERIA FOREIGN KEY (COD_CARRERA) 
	REFERENCES CARRERAS (COD_MATERIA)
		ON UPDATE NO ACTION
		ON DELETE NO ACTION,
	
	CONSTRAINT FK_MT_COD_MATERIA FOREIGN KEY (COD_CARRERA)
	REFERENCES CARRERAS (COD_MATERIA)
		ON UPDATE NO ACTION
		ON DELETE NO ACTION,








-- MATERIAS_ABIERTAS

ALTER TABLE MATERIAS_ABIERTAS
	ADD CONSTRAINT PK_MATERIA_ABIERTA PRIMARY KEY (COD_MATERIA_ABIERTA);
/*
ALTER TABLE HORARIOS
	ADD CONSTRAINT PK_DIA PRIMARY KEY (DIA);

ALTER TABLE HORARIOS
	ADD CONSTRAINT PK_HORA_INICIO PRIMARY KEY (HORA_INICIO);

ALTER TABLE HORARIOS
	ADD CONSTRAINT PK_HORA_FIN PRIMARY KEY (HORA_FIN);
*/

ALTER TABLE MATRICULAS
	ADD CONSTRAINT PK_NUM_RECIBO PRIMARY KEY (NUM_RECIBO);

-- __________________ FK __________________

ALTER TABLE MATERIAS_CARRERAS
	ADD 

ALTER TABLE MATERIAS_CARRERAS
	ADD CONSTRAINT FK_MATERIA FOREIGN KEY (COD_MATERIA) REFERENCES MATERIAS (COD_MATERIA)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION;

/*
REQUISITO
CORREQUISITO
*/

ALTER TABLE MATERIAS_ABIERTAS
	ADD CONSTRAINT FK_MATERIA_CARRERA FOREIGN KEY (COD_MATERIA_CARRERA) REFERENCES MATERIAS_CARRERAS (COD_MATERIA_CARRERA)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION;

ALTER TABLE MATERIAS_ABIERTAS
	ADD CONSTRAINT FK_PROFESOR FOREIGN KEY (COD_PROFESOR) REFERENCES PROFESORES (COD_PROFESOR)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION;

ALTER TABLE MATERIAS_ABIERTAS
	ADD CONSTRAINT FK_MATERIA_CARRERA FOREIGN KEY (COD_MATERIA_CARRERA) REFERENCES MATERIAS_CARRERAS (COD_MATERIA_CARRERA)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION;

ALTER TABLE HORARIOS
	ADD CONSTRAINT FK_MATERIA_ABIERTA FOREIGN KEY (COD_MATERIA_ABIERTA) REFERENCES MATERIAS_ABIERTAS (COD_MATERIA_ABIERTA)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION;

ALTER TABLE MATRICULAS
	ADD CONSTRAINT FK_CARNET FOREIGN KEY (CARNET) REFERENCES ESTUDIANTES (CARNET)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION;

ALTER TABLE DETALLE_MATRICULAS
	ADD CONSTRAINT FK_NUM_RECIBO FOREIGN KEY (NUM_RECIBO) REFERENCES MATRICULAS (NUM_RECIBO)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION;

ALTER TABLE DETALLE_MATRICULAS
	ADD CONSTRAINT FK_COD_MATERIA_ABIERTA FOREIGN KEY (COD_MATERIA_ABIERTA) REFERENCES MATERIAS_ABIERTAS (COD_MATERIA_ABIERTA)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION;

-- ____________________ AGREGAR VALORES POR DEFECTO ____________

-- MATERIAS_ABIERTAS

ALTER TABLE MATERIAS_ABIERTAS
	ADD DEFAULT 30 FOR CUPO,
	CONSTRAINT CHK_COSTO CHECK (COSTO > 0),
	CONSTRAINT CHK_ANIO CHECK (ANIO >= year(getdate())),
	CONSTRAINT CHK_MAXIMO_DESCUENTO CHECK (MAXIMO_DESCUENTO >= 0 AND MAXIMO_DESCUENTO < 100);

-- HORARIOS

ALTER TABLE HORARIOS
	ADD CONSTRAINT CHK_DIA CHECK (DIA = upper(DIA) AND DIA IN ('L','K','M','J','V','S','D'));

-- MATRICULAS

ALTER TABLE MATRICULAS
	ADD DEFAULT getdate() FOR FECHA,
	CONSTRAINT CHK_MONTO CHECK (MONTO >= 0),
	CONSTRAINT CHK_DESCUENTO CHECK (DESCUENTO >= 0),
	CONSTRAINT DF_GRADO DEFAULT 'ACT' FOR ESTADO,
	CONSTRAINT CHK_ESTADO CHECK (ESTADO = upper(ESTADO) AND ESTADO IN ('ACT','INA'));

-- DETALLE_MATRICULAS

ALTER TABLE DETALLE_MATRICULAS
	ADD DEFAULT 0 FOR PORCENTAJE_DESCUENTO,
	CONSTRAINT CHK_PORCENTAJE_DESCUENTO CHECK (PORCENTAJE_DESCUENTO > 0 AND PORCENTAJE_DESCUENTO < 100),
	DEFAULT 0 FOR NOTA_FINAL,
	CONSTRAINT CHK_NOTA_FINAL CHECK (NOTA_FINAL > 0 AND NOTA_FINAL <= 100),
	DEFAULT 'ACT' FOR ESTADO,
	CONSTRAINT CHK_ESTADO CHECK (ESTADO = upper(ESTADO) AND ESTADO IN ('ACT','RET','APR','REP'));